### ISSUE TITLE
Technical planning session - framework discussion and confirmation

### ISSUE THREAD

**Issue by joelriley** [joelriley/locationapp#3]
Discuss research and analysis findings into customizing Bootstrap vs using a simple framework like GetSkeleton, confirm which framework will be used going forward

**Comment by joelriley** [comment]
I have a new code base I will upload this evening - its adapted from a minimal framework, I have teh base plus key features available in separate files, we can assemble them and edit then do the CSS

**Comment by kouksot** [comment]
I will css everything after the assembly.
