### ISSUE TITLE
Post wireframe layouts to Github

### ISSUE THREAD

**Issue by joelriley** [joelriley/locationapp#4]
Post the layouts and review recent user testing feedback

**Comment by kouksot** [comment]
![tasks-wireframes](https://cloud.githubusercontent.com/assets/14094796/14864243/c649e0f4-0cc1-11e6-985c-d4d03b0db7e5.png)

**Comment by kouksot** [comment]
These were the first wireframes out of which paper prototypes were made for user testing

**Comment by joelriley** [comment]
I've been doing a bit of research on the menu bar Sotiris I think we can simplify things
