### ISSUE TITLE
Conduct final user testing session discuss results 

### ISSUE THREAD

**Issue by joelriley** [joelriley/locationapp#5]
Discuss how the testing results affects design layouts, development and testing

**Comment by kouksot** [comment]
The user testing was conducted successfully and we have the latest design iteration product in wireframes.

**Comment by kouksot** [comment]
Final High fidelity mockups are in production will be posted asap

**Comment by joelriley** [comment]
Some updates to the design may come as part of the testing results

**Comment by joelriley** [comment]
Updates should be minor mostly labeling of call to actions
