### ISSUE TITLE
Outstanding Style Elements

### ISSUE THREAD

**Issue by joelriley** [joelriley/locationapp#6]
Button color values
Location Status OK graphic or CSS style
Emergency and Call Home "Calling" graphic
Locate Map graphic
Analytics chart graphic
Verify top banner color values
Confirm font style

**Comment by kouksot** [comment]
locate button & Top nav bar color #00618c
health stats button color #fb9031
emergency call button  color #ff6663
call patient color #49aad7
 font style Roboto condensed, sans serif  30pt

**Comment by kouksot** [comment]
![sojo](https://cloud.githubusercontent.com/assets/14094796/15099741/d28106f6-1566-11e6-93d8-bca28e41fa2c.jpg)

**Comment by kouksot** [comment]
![alert-signal](https://cloud.githubusercontent.com/assets/14094796/15231985/f3735aec-18a6-11e6-9597-90860e10dbec.png)
![ok-signal](https://cloud.githubusercontent.com/assets/14094796/15231986/f3a232ea-18a6-11e6-9dc9-55450a046a29.png)
![warning-signal](https://cloud.githubusercontent.com/assets/14094796/15231987/f3a37e20-18a6-11e6-95fa-a7fc6c30865a.png)

**Comment by kouksot** [comment]
I will upload them also in the assets along with the other images of the health stats and map mockup

**Comment by kouksot** [comment]
Also working on the main. css and the index. Uploading the fianl version of layout today or tomorrow
