### ISSUE TITLE
Final Prototype Styling Configuration

### ISSUE THREAD

**Issue by joelriley** [joelriley/locationapp#8]
The following styling items are outstanding to adjust and implement as part of the final prototype configuration:

Analytics image
Signal settings safe distance field
Map image interaction
Back font rendering 
Button hover state
Account settings - submit
Remove footer

**Comment by kouksot** [comment]
Analytics image added
distance field added
iframe interactive map added
checking the font atm
submit button added
removed footer
hover state fixed on 'locate'
